server {
    listen 80;
    server_name _;

    location = / {
        return 301 /mgnt/;
    }

    location = /mgnt {
        return 301 /mgnt/;
    }

    location ^~ /mgnt/assets/ {
        root /usr/share/nginx/html;
        try_files $uri =404;
    }

    location = /mgnt/ {
        root /usr/share/nginx/html;
        try_files /mgnt/index.html =404;
    }
}
