FROM node:20-alpine AS build
WORKDIR /app
COPY frontend/ui/package.json frontend/ui/package-lock.json ./
RUN npm ci
COPY frontend/ui/ ./
RUN npm run build

FROM nginx:1.27-alpine AS serve
WORKDIR /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist ./mgnt/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
